/**
 * Merges every imported location file into the atlas the app ships.
 *
 * Deduplicates across sources (the same venue often appears in more than one
 * guide) by name and rounded coordinates, merging their categories. Every
 * place is attributed to the house account and carries NO review, score or
 * description — members supply all of that.
 *
 *   npx tsx scripts/build-imported-seed.ts
 *
 * Writes public/atlas-places.json (loaded by the app at runtime) and
 * supabase/seed-imported.sql (only needed if the places are ever moved into
 * the database instead).
 */
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { ImportedPlace } from './import-lefooding'

const HERE = dirname(fileURLToPath(import.meta.url))
const DATA = join(HERE, 'data')
const HOUSE_ID = '00000000-0000-4000-a000-000000000001'
const EPOCH = '2026-01-01T00:00:00.000Z'

const q = (s: string): string => `'${s.replace(/'/g, "''")}'`

/** Stable id per venue so re-running the import never duplicates rows. */
function uuidFrom(seed: string): string {
  // FNV-1a, expanded to 32 hex chars — deterministic and collision-safe enough
  // for a few thousand venues.
  let h1 = 0x811c9dc5
  let h2 = 0x01000193
  for (let i = 0; i < seed.length; i++) {
    h1 ^= seed.charCodeAt(i)
    h1 = Math.imul(h1, 0x01000193) >>> 0
    h2 ^= seed.charCodeAt(seed.length - 1 - i)
    h2 = Math.imul(h2, 0x85ebca6b) >>> 0
  }
  const block = (n: number) => n.toString(16).padStart(8, '0')
  const hex = (block(h1) + block(h2) + block(h1 ^ h2) + block((h1 + h2) >>> 0)).slice(0, 32)
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-4${hex.slice(13, 16)}-a${hex.slice(17, 20)}-${hex.slice(20, 32)}`
}

function load(file: string): ImportedPlace[] {
  const path = join(DATA, file)
  if (!existsSync(path)) {
    console.log(`(skipping ${file} — not present)`)
    return []
  }
  return JSON.parse(readFileSync(path, 'utf8')) as ImportedPlace[]
}

/**
 * Order matters: on a duplicate the first source seen keeps its name and
 * address, so the tightly-edited guides come before the broader community
 * sources, which are numerous but looser about naming.
 */
const SOURCES = [
  'lefooding-places.json',
  'gaultmillau-places.json',
  'wikidata-places.json',
  '50best-places.json',
  'laliste-places.json',
  'eater-places.json',
  'timeout-places.json',
  'wikivoyage-places.json',
]

/** Sources spell the same country several ways; the map shows only one. */
const COUNTRY_FIXES: [RegExp, string][] = [
  [/^(U\.?S\.?A\.?|US|USA|United States of America)$/i, 'United States'],
  [/^(U\.?K\.?|Great Britain|England)$/i, 'United Kingdom'],
  [/^(UAE|U\.A\.E\.)$/i, 'United Arab Emirates'],
  [/^(Holland|The Netherlands)$/i, 'Netherlands'],
  [/^Czech Republic$/i, 'Czechia'],
  // Le Fooding is a French publication and names countries in French.
  [/^Belgi(que|ë)$/i, 'Belgium'],
  [/^(Allemagne|Deutschland)$/i, 'Germany'],
  [/^(Espagne|España)$/i, 'Spain'],
  [/^(Italie|Italia)$/i, 'Italy'],
  [/^(Pays-Bas)$/i, 'Netherlands'],
  [/^(Suisse|Schweiz)$/i, 'Switzerland'],
  [/^(Royaume-Uni)$/i, 'United Kingdom'],
]

function normaliseLocality(locality: string): string {
  const parts = locality.split(',').map((s) => s.trim()).filter(Boolean)
  if (parts.length === 0) return locality
  const last = parts[parts.length - 1]
  for (const [pattern, canonical] of COUNTRY_FIXES) {
    if (pattern.test(last)) {
      parts[parts.length - 1] = canonical
      break
    }
  }
  return parts.join(', ')
}

function run() {
  const all = SOURCES.flatMap(load)
  for (const p of all) p.locality = normaliseLocality(p.locality)

  const byKey = new Map<string, ImportedPlace>()
  for (const p of all) {
    if (!p.name?.trim() || !Number.isFinite(p.lat) || !Number.isFinite(p.lng)) continue
    const key = `${p.name.toLowerCase().replace(/[^a-z0-9]/g, '')}|${p.lat.toFixed(3)}|${p.lng.toFixed(3)}`
    const existing = byKey.get(key)
    if (existing) {
      existing.categories = [...new Set([...existing.categories, ...p.categories])]
    } else {
      byKey.set(key, { ...p, categories: [...new Set(p.categories)] })
    }
  }

  const places = [...byKey.values()]
  const bySource = places.reduce<Record<string, number>>((acc, p) => {
    acc[p.source] = (acc[p.source] ?? 0) + 1
    return acc
  }, {})

  const lines: string[] = [
    '-- Generated by scripts/build-imported-seed.ts — do not edit by hand.',
    '-- Venue LOCATIONS only: name, address, coordinates. No reviews, scores or',
    '-- descriptions are imported; every rating in Curated comes from a member.',
    '-- Run AFTER 0001_init.sql and the later migrations.',
    '',
    '-- House account must exist (also created by seed.sql).',
    `insert into public.profiles (id, username, display_name, onboarded, is_seed)`,
    `values ('${HOUSE_ID}', 'curated', 'Curated', false, true) on conflict do nothing;`,
    '',
  ]

  // Multi-row inserts keep the file small enough to paste in one go.
  const CHUNK = 250
  for (let i = 0; i < places.length; i += CHUNK) {
    const chunk = places.slice(i, i + CHUNK)
    lines.push(
      'insert into public.places (id, city_id, locality, name, categories, lat, lng, address, description, created_by, created_at) values',
    )
    lines.push(
      chunk
        .map((p) => {
          const id = uuidFrom(`${p.source}|${p.name}|${p.lat.toFixed(5)}|${p.lng.toFixed(5)}`)
          // Provenance only — a factual credit to where the listing came
          // from, never the guide's own words about the place.
          const credit = `Listed by ${p.source}`
          return `('${id}', null, ${q(p.locality)}, ${q(p.name)}, '{${p.categories.join(',')}}', ${p.lat}, ${p.lng}, ${q(p.address)}, ${q(credit)}, '${HOUSE_ID}', '${EPOCH}')`
        })
        .join(',\n'),
    )
    lines.push('on conflict do nothing;', '')
  }

  const out = join(HERE, '..', 'supabase', 'seed-imported.sql')
  mkdirSync(dirname(out), { recursive: true })
  writeFileSync(out, lines.join('\n') + '\n')

  // The app fetches this at runtime; short keys because the file is shipped
  // to phones and every byte is repeated once per place.
  const atlas = places.map((p) => ({
    n: p.name,
    c: p.categories,
    y: Number(p.lat.toFixed(6)),
    x: Number(p.lng.toFixed(6)),
    a: p.address,
    l: p.locality,
    s: p.source,
  }))
  const atlasPath = join(HERE, '..', 'public', 'atlas-places.json')
  mkdirSync(dirname(atlasPath), { recursive: true })
  writeFileSync(atlasPath, JSON.stringify(atlas))

  console.log(`merged ${all.length} → ${places.length} unique places`)
  for (const [src, n] of Object.entries(bySource).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${src}: ${n}`)
  }
  const mb = (statSync(atlasPath).size / 1024 / 1024).toFixed(2)
  console.log(`wrote ${atlasPath} (${mb} MB)`)
  console.log(`wrote ${out}`)
}

run()
