/**
 * Renders the PRODUCTION seed into supabase/seed.sql:
 * the 5 cities and the 88 curated venues, attributed to a single house
 * account that also owns the founding invite code.
 *
 * Deliberately EXCLUDES the 8 demo personas, their reviews, follows and
 * credit entries. Those exist to make local demo mode feel alive; loading
 * fabricated scores into the real database would feed the taste engine and
 * skew every real member's match percentages — the opposite of the
 * accurate-profiles-first rollout this app is built for.
 *
 * Demo mode is unaffected: it reads src/seed/* directly and never touches
 * this file.
 *
 * Run `npm run generate-seed-sql` after editing anything under src/seed/,
 * then re-run seed.sql in the Supabase SQL editor.
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { SEED_CITIES } from '../src/seed/cities'
import { SEED_PLACES } from '../src/seed/places'
import { inviteId } from '../src/seed/ids'

/** The house account: curator of the seeded venues, owner of the first invite. */
const HOUSE_ID = '00000000-0000-4000-a000-000000000001'
const HOUSE_USERNAME = 'curated'
const HOUSE_NAME = 'Curated'
const FOUNDING_CODE = 'CURATED1'
const EPOCH = '2026-01-01T00:00:00.000Z'

const q = (s: string | null): string => (s === null ? 'NULL' : `'${s.replace(/'/g, "''")}'`)

const lines: string[] = [
  '-- Generated by scripts/generate-seed-sql.ts — do not edit by hand.',
  '-- Run AFTER 0001_init.sql. Idempotent (on conflict do nothing).',
  '--',
  '-- Contains: 5 cities, 88 curated venues, 1 house account, 1 founding invite.',
  '-- Contains NO member reviews — every score in your database will come',
  '-- from a real person.',
  '',
]

for (const c of SEED_CITIES) {
  lines.push(
    `insert into public.cities (id, name, country, center_lat, center_lng, default_zoom) values (${q(c.id)}, ${q(c.name)}, ${q(c.country)}, ${c.centerLat}, ${c.centerLng}, ${c.defaultZoom}) on conflict do nothing;`,
  )
}
lines.push('')

// House account. onboarded = false keeps it out of the member directory and
// out of follow suggestions; it exists to own the seeded venues and the
// first invite code.
lines.push(
  '-- House account — owns the seeded venues and the founding invite code.',
  `insert into public.profiles (id, username, display_name, avatar_color, bio, interests, home_city, is_admin, invited_by, onboarded, is_seed, created_at) values (${q(HOUSE_ID)}, ${q(HOUSE_USERNAME)}, ${q(HOUSE_NAME)}, '#1c1c1e', ${q('Places worth your time, gathered to start the atlas off.')}, '{}', NULL, false, NULL, false, true, ${q(EPOCH)}) on conflict do nothing;`,
  '',
  '-- The founding invite. Sign up with this code using your admin email.',
  `insert into public.invite_codes (id, code, owner_id, created_at) values (${q(inviteId(1))}, ${q(FOUNDING_CODE)}, ${q(HOUSE_ID)}, ${q(EPOCH)}) on conflict do nothing;`,
  '',
)

for (const p of SEED_PLACES) {
  lines.push(
    `insert into public.places (id, city_id, locality, name, categories, lat, lng, address, description, created_by, created_at) values (${q(p.id)}, ${q(p.cityId)}, ${q(p.locality)}, ${q(p.name)}, '{${p.categories.join(',')}}', ${p.lat}, ${p.lng}, ${q(p.address)}, ${q(p.description)}, ${q(HOUSE_ID)}, ${q(EPOCH)}) on conflict do nothing;`,
  )
}

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'supabase', 'seed.sql')
writeFileSync(out, lines.join('\n') + '\n')
console.log(
  `Wrote ${out}: ${SEED_CITIES.length} cities, ${SEED_PLACES.length} venues, 1 house account, 1 invite code, 0 reviews.`,
)
